apiVersion: v1
kind: Service
metadata:
  name: nginx-service-codebuild
spec:
  selector:
    app: nginx-codebuild
  ports:
    - name: web
      port: 80
      targetPort: 80
  #type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-codebuild
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-codebuild
    spec:
      tolerations:
      - key: "spotInstance"
        operator: "Equal"
        value: "true"
        effect: "PreferNoSchedule"
      containers:
      - name: nginx-codebuild
        image: nginx
        env:
        - name: DEPLOYED_FROM
          value: CodeBuild
        ports:
        - containerPort: 80
